kind: pipeline
name: docker-amd

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: samuelph/feed2toot
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD

---
kind: pipeline
name: docker-arm

platform:
  os: linux
  arch: arm

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: samuelph/feed2toot
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD
