kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: samuelph/feed2toot
      username:
        from_secret: USERNAME
      password:
        from_secret: PASSWORD